### ISSUE TITLE
BrowserView render on top of everything

### ISSUE THREAD

**Issue by Akravator91** [IanPhilips/UnityAndroidVRARBrowser#11]
Hi2.

Small question, Does the BrowserView has to be rendered on top of everything?
I have a keyboard that use a canvas renderer and as well as some other game object with default unity material.
And the BrowserView gameobject is always render in top of the canvas as well as every other game object.

**Comment by IanPhilips** [comment]
Great question. There are two ways that I know to get around this. 1.
Continue to use your canvas based keyboard and either change the size of
the browser when it comes up or keep it below/next to the browser so they
never overlap.
2. Use a complete keyboard image rendered onto its own ovrsurfaceoverlay
with another ovrsurfaceoverlay image that frames the key in focus.

**Comment by Akravator91** [comment]
Hi Ian,

Thank you for your suggestion and replying my message.

Your suggestion might take care of the overlapping of the Keyboard's issue.
However, how about other 3D object. For example; if there is a player avatar or some other GameObjects?

**Comment by IanPhilips** [comment]
You'll want to read up on ovroverlays here:
https://developer.oculus.com/documentation/unity/unity-ovroverlay/

In short, the overlays are rendered directly over the eye buffer so only
other ovroverlays can be rendered over themselves. Traditional objects in
unity will always be underneath.

**Comment by Akravator91** [comment]
Been trying for a week... (っ- ‸ – ς)
and I havent find a good way to deal with the overlay.

Does the browser has to use OVRoverlay?

**Comment by IanPhilips** [comment]
Yes, the browser has to use the OVROverlay. What are you having trouble with? Using more OVROverlays is the only option to display other UI elements over the browser, or you can hide (scaling or moving) the browser.
