### ISSUE TITLE
Can I use this pluign for my AR project?

### ISSUE THREAD

**Issue by mfiddin** [IanPhilips/UnityAndroidVRARBrowser#12]
I would like to display my IoT monitoring (web-based) kind of attach to an gameobject, is it possible?

**Comment by mfiddin** [comment]
I mean i will not use oculus just as AR app in andorid, i want to display my specific html page on my AR

**Comment by IanPhilips** [comment]
You should be able to use it as long as you include the Oculus Plugin in your project. I think that it should work on mobile. You can read up here on the integration: https://developer.oculus.com/downloads/package/unity-integration/

Right now the plugin included in the demo project is not the newest one, however so you'll have to see if it works.

**Comment by mfiddin** [comment]
I have tried import the package, then just put the prefab called BrowserView but nothing happened when I play
