### ISSUE TITLE
Need a simple sample

### ISSUE THREAD

**Issue by mfiddin** [IanPhilips/UnityAndroidVRARBrowser#14]
I am sorry for bothering you, but finally I found most suitable plugin for my project. I have tried yours but still getting problem. Can you make a simple sample scene that only show this web browser in a plane without oculus integration, I mean by using the camera instead. I will be really grateful if you could help me...I have been struggling with my diploma final project. 

:(   :(

**Comment by IanPhilips** [comment]
It's only possible with the oculus integration, sorry.
