### ISSUE TITLE
Can I 'request desktop site'?

### ISSUE THREAD

**Issue by DaveAccenture** [IanPhilips/UnityAndroidVRARBrowser#15]
Some sites will only give you the mobile version, but there are times when you really just need the desktop version (Microsoft Teams and Jit.si from my tests). Any way to do that?

**Comment by DaveAccenture** [comment]
Not yet. Sorry. Is this toggle the way to request the desktop version? As I understand it, this sends headers that indicate that the browser is desktop rather than mobile to fool the server into sending that version. I may be wrong...

**Comment by IanPhilips** [comment]
Is there another way to get the desktop site? That's what I use and it works.
