### ISSUE TITLE
Decouple from OVROverlay 

### ISSUE THREAD

**Issue by NoviaDroid** [IanPhilips/UnityAndroidVRARBrowser#16]
The webview is rendered by OVROverlay, and it will always render in front of everything else (overlay is in front of eye texture)

So when converted the scene to use controllers input instead of gaze, the controller is always looks behind the webview, and looks wired.

 And because this is based on oculus sdk, it is hard to use in other mobile vr platforms such as daydream and pico.

Maybe there is a way to get rid of oculus sdk?

**Comment by IanPhilips** [comment]
You can use other [OVROverlays](https://developer.oculus.com/documentation/unity/unity-ovroverlay/?locale=en_US) (up to 15) to render over the browser's. 

With respect to the sdk: https://github.com/IanPhilips/UnityAndroidVRARBrowser/issues/8#issuecomment-625343189

**Comment by NoviaDroid** [comment]
Yes,but it will be wired if render a controller as a overlay? It would be 3D look -> 2D look? I haven't tried it yet.

**Comment by IanPhilips** [comment]
mmm yeah true, I believe the OVROverlays can have other shapes than quads at least but not sure which.

**Comment by CallumFerguson** [comment]
You can also use a OVROverlay with the Current Overlay Type set to Underlay. This will render under everything which means you will not see it, but there is a built in shader to punch through the screen to show the underlay. The result is the OVROverlay functions just like if the Geckoview was rendered to a texture on a quad. 

https://developer.oculus.com/documentation/unity/unity-ovroverlay/?locale=en_US

**Comment by IanPhilips** [comment]
If that works that would be excellent! Thanks for the tip. Hopefully the punched hole in the screen still allows other things closer to the cameras to be seen.

**Comment by CallumFerguson** [comment]
It does work. I am currently using that in my project and you can't tell that it isn't a a quad with a texture.

**Comment by IanPhilips** [comment]
Beautiful, it seems like the demo scene should have this by default. If you configure it and submit a PR I'd be grateful. Alternatively you could detail the steps in the README and submit a PR.

**Comment by CallumFerguson** [comment]
[Submitted pull request.](https://github.com/IanPhilips/UnityAndroidVRARBrowser/pull/17) Several files files changed automatically even when opened with the correct version of Unity. Hopefully that doesn't mess anything up.

**Comment by IanPhilips** [comment]
Nice work! I just confirmed things are working correctly, thanks!
