### ISSUE TITLE
Oculus quest?

### ISSUE THREAD

**Issue by skelder** [IanPhilips/UnityAndroidVRARBrowser#9]
did anyone try to run this on oculus quest?

I am having trouble running this on Oculus Quest, the main problem with it is that logcat shows no errors whenever the app crashes.

Also I noticed that portion of the log complaining about BasicActivity, which did not make much sense to me,due to me being fairly new to android system.

`04-02 23:25:56.530 10637 10654 I AndroidUnity: Hi, new instance created

04-02 23:25:56.530 10637 10654 I AndroidUnity: CREATING FRAGMENT

04-02 23:25:56.531 10637 10637 D AndroidUnity: On Create View!

04-02 23:25:56.531 10637 10637 D AndroidUnity: On inflate  View!

04-02 23:25:56.537 10637 10637 I AndroidUnity: BasicActivity not found! We are a library and not an application

04-02 23:25:56.538 10637 10637 I AndroidUnity: activity is not null, setting basic selection delegate and using floating bar: true

04-02 23:25:56.538 10637 10637 I AndroidUnity: CREATING runtime

04-02 23:25:56.552 10637 10654 D AndroidUnity: My unity callback is set

04-02 23:25:56.569 10637 10637 I AndroidUnity: CREATING sessions hashmap`

**Comment by IanPhilips** [comment]
Hmm, I haven't tried and I don't have one unfortunately. Doesn't look like there're any errors in those logs though. It could be quest requires a certain version of the Oculus plugin? as of right now the plugin in this repo is I think around v30. I tried updating the plugin but ran into too many problems. I know it can be done though as I did it in another project.

**Comment by skelder** [comment]
Quick update.

I managed to make it run on oculus quest, by using the exact same version of unity and without updating the oculus integration

I am going to try to find the exact cause for the crash, but i suspect it's just api calls being messed up by the updates.

**Comment by skelder** [comment]
It turned out to be very simple issue of additional variable that was causing a NullRefernce error,
Which in turn made Unity do what it does best, flip upside down and collapse on itself.

Jokes aside, you can safely upgrade Unity and oculus integration. 
I managed to make the demo run on Unity 2019.3.8 and Oculus integration 15 (I think they changed the versioning scheme somewhere done the line, this version number is from package manager my assets window).

Steps I took to achieve that:

1. Load original project with original unity version 
(Oculus may ask you to restart at this point complaining about some changes)

2. Close Unity and delete Oculus folder from Assets

3. Open unity 2 times to let Unity realize we just snitched one it's internal organs.

4. Import shiny new Oculus integration and follow it's demands and reboot

5. Close Unity then Bump up the unity version from unity hub.

To be honest, up to this part is not really important and can be done interchangeably I believe.

**_6. Open the  Demo Scene -> Select EventSystem -> Drag "OVRGazePointer" from scene hierarchy into Cursor variable on the "OVR Input Module" Component_**

And.... that's it.

I really feel dumb for spending hours looking through adb logcat logs, when I could have just run the damn thing inside editor and see the damn NullReference counter pile up on console logs.

One Side note is that the button for clicking changes to 'A' button on quest controllers once upgrade is done, so you don't have to squeeze 'em triggers hard. Probably due to changes in how unity is handling the inputs from Controllers. Gotta love those API changes.
